apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-item-api
  labels:
    run: udagram-feed-itemr-api
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: udagram-feed-item-api
